name: Release markdown-scanner Binary

permissions:
  contents: write # Grant write access for releases

on:
  push:
    tags:
      - "v[0-9]+.*" # Triggers on tags like v1.0.7

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Linux and Windows Cross Compilers
        run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

      - name: Build the executable
        run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

      - name: Tar x86_64 binary
        run: tar -czvf markdown-scanner-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release markdown-scanner

      - name: Zip windows binary
        run: zip -j markdown-scanner-windows.zip target/x86_64-pc-windows-gnu/release/markdown-scanner.exe

      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 markdown-scanner-gnu-linux-x86_64.tar.gz > markdown-scanner-gnu-linux-x86_64.tar.gz.sha256
          shasum -a 256 markdown-scanner-windows.zip > markdown-scanner-windows.zip.sha256

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            markdown-scanner-gnu-linux-x86_64.tar.gz
            markdown-scanner-windows.zip
            markdown-scanner-gnu-linux-x86_64.tar.gz.sha256
            markdown-scanner-windows.zip.sha256
